const recipes = [
  {
    id: 1,
    image: "https://img.spoonacular.com/recipes/650126-312x231.jpg",
    likes: 25,
    title: "Spaghetti Carbonara",
    summary:
      "Spaghetti Carbonara is a classic pasta dish that is quick, easy, and delicious. It is made with simple ingredients like eggs, cheese, pancetta, and black pepper. The key to a good carbonara is to use high-quality ingredients and to cook the pasta al dente. This recipe is perfect for a weeknight dinner or a special occasion. Enjoy!",
  },
  {
    id: 2,
    image: "https://img.spoonacular.com/recipes/658276-312x231.jpg",
    likes: 42,
    title: "Classic Margherita Pizza",
    summary:
      "Margherita pizza is a classic Italian dish that is simple, delicious, and easy to make. It is made with a thin crust, tomato sauce, fresh mozzarella cheese, basil, and olive oil. The key to a good margherita pizza is to use high-quality ingredients and to cook it at a high temperature. This recipe is perfect for a weeknight dinner or a special occasion. Enjoy!",
  },
  {
    id: 3,
    image: "https://img.spoonacular.com/recipes/671594-312x231.jpg",
    likes: 18,
    title: "Chicken Alfredo Pasta",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 4,
    image: "https://img.spoonacular.com/recipes/652304-312x231.jpg",
    likes: 55,
    title: "Vegan Buddha Bowl",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 5,
    image: "https://img.spoonacular.com/recipes/652641-312x231.jpg",
    likes: 37,
    title: "Beef Stroganoff",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 6,
    image: "https://img.spoonacular.com/recipes/662089-312x231.jpg",
    likes: 29,
    title: "Mediterranean Salad",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 7,
    image: "https://img.spoonacular.com/recipes/665486-312x231.jpg",
    likes: 64,
    title: "Pan-Seared Salmon",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 8,
    image: "https://img.spoonacular.com/recipes/655418-312x231.jpg",
    likes: 45,
    title: "Avocado Toast",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 9,
    image: "https://img.spoonacular.com/recipes/656592-312x231.jpg",
    likes: 33,
    title: "Teriyaki Chicken Bowl",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 10,
    image: "https://img.spoonacular.com/recipes/649991-312x231.jpg",
    likes: 50,
    title: "Chocolate Lava Cake",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 11,
    image: "https://img.spoonacular.com/recipes/649986-312x231.jpg",
    likes: 20,
    title: "Caesar Salad",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 12,
    image: "https://img.spoonacular.com/recipes/648733-312x231.jpg",
    likes: 72,
    title: "Homemade Tacos",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 13,
    image: "https://img.spoonacular.com/recipes/648435-312x231.jpg",
    likes: 15,
    title: "Mushroom Risotto",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 14,
    image: "https://img.spoonacular.com/recipes/648213-312x231.jpg",
    likes: 40,
    title: "Grilled Cheese Sandwich",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 15,
    image: "https://img.spoonacular.com/recipes/647760-312x231.jpg",
    likes: 61,
    title: "Pancakes with Syrup",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 16,
    image: "https://img.spoonacular.com/recipes/647717-312x231.jpg",
    likes: 53,
    title: "Shrimp Fried Rice",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
  {
    id: 17,
    image: "https://img.spoonacular.com/recipes/647426-312x231.jpg",
    likes: 19,
    title: "Quinoa Salad",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac",
  },
];

export default recipes;
